export const GET_POKEMON_REQUEST = 'GET_POKEMONS_REQUEST'
export const GET_POKEMON_SUCCESS = 'GET_POKEMONS_SUCCESS'
export const GET_POKEMON_FAIL = 'GET_POKEMONS_FAIL'
export const SET_POKEMON = 'SET_POKEMON'

export const GET_EVOLUTION_FORMS_REQUEST = 'GET_EVOLUTION_FORMS_REQUEST'
export const GET_EVOLUTION_FORMS_SUCCESS = 'GET_EVOLUTION_FORMS_SUCCESS'
export const GET_EVOLUTION_FORMS_FAIL = 'GET_EVOLUTION_FORMS_FAIL'
export const SET_EVOLUTION_FORMS = 'SET_EVOLUTION_FORMS'
